# Generated by Django 4.0.2 on 2022-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contactmail', models.CharField(max_length=30)),
                ('cellphone', models.PositiveIntegerField()),
            ],
        ),
    ]
