# Generated by Django 4.0.2 on 2022-02-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurantes_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='restaurant_image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='view'),
        ),
    ]
